"""empty message

Revision ID: 122bbaeb4774
Revises: eeee99d6aa3f
Create Date: 2019-09-08 21:30:23.486209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '122bbaeb4774'
down_revision = 'eeee99d6aa3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_post', sa.Column('author_id', sa.Integer(), nullable=True))
    op.drop_constraint(u'blog_post_author_fkey', 'blog_post', type_='foreignkey')
    op.create_foreign_key(None, 'blog_post', 'users', ['author_id'], ['id'])
    op.drop_column('blog_post', 'author')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_post', sa.Column('author', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'blog_post', type_='foreignkey')
    op.create_foreign_key(u'blog_post_author_fkey', 'blog_post', 'users', ['author'], ['id'])
    op.drop_column('blog_post', 'author_id')
    # ### end Alembic commands ###
